title: Arhaan Jain
description: The personal website of Arhaan Jain.
url: "https://gokuussg.github.io"
baseurl: "/arhaanjain.github.io"

author:
  name: Arhaan Jain
  email: "arhaanjain3@gmail.com"

theme: jekyll-theme-minimal
